### ISSUE TITLE
Self-Propelled Rods

### ISSUE THREAD

**Issue by navdeeprana** [glotzerlab/hoomd-blue#1056]
## Description

I would like to simulate self-propelled rods using HOOMD-blue. Here's a reference paper : https://arxiv.org/pdf/1807.00294.pdf
I already have my own linkedlist based implementation, but it only runs on a single cpu. I would like to use features available in
HOOMD-blue to have MPI/GPU support. I am up to implement it myself, but need help to figure out how to proceed.

## Details

The particles are self-propelled 2D rods with center `(rx,ry)`, unit width, a length `l`and orientation `theta`. The rods move in the direction specified by their orientation. Inter-rod interactions are contact based and operate as follows:

- Find the shortest distance `d` between two rods.
- If `d` is less than the sum of half widths of the rods, the rods repel each other with a force proportional to the overlap.

**Comment by joaander** [comment]
@navdeeprana HOOMD-blue v3.0.0-beta.7 already implements the active force you describe. For volume-excluding inter-particle forces, you could use `hoomd.md.constrain.Rigid` and a collection of WCA spheres or an ellipsoid with `hoomd.md.pair.aniso.GayBerne`. You could also approximate the rods with an ellipsoid or polyhedron using the upcoming feature in #992 (https://doi.org/10.1063/5.0019735).

The specific interaction you propose does not conserve energy due to the discontinuity in the torque when the particles rotate, so I would not include such an interaction in HOOMD-blue itself. You are welcome to implement your potential in a separate plugin.
