### ISSUE TITLE
Box.lattice_vectors and Box.matrix are similar in functionality but differ in implementation

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#1070]
## Description

It appears that `Box.lattice_vectors` and `Box.matrix` are two different implementations of the same thing, but transposed from one another. Lattice vectors calls into C++ but the matrix is implemented in pure Python. The matrix property can be set, while lattice vectors cannot. The docs are not clear about the relationship between the two. We should consolidate the implementation even if we keep both properties (and document the transpose between them). I’m happy to contribute a fix for this if maintainers can help decide on what to do.

https://github.com/glotzerlab/hoomd-blue/blob/d46de2f693cbc597dff4a64406476cb161b0f742/hoomd/box.py#L354-L362

https://github.com/glotzerlab/hoomd-blue/blob/d46de2f693cbc597dff4a64406476cb161b0f742/hoomd/box.py#L380-L397

https://github.com/glotzerlab/hoomd-blue/blob/d46de2f693cbc597dff4a64406476cb161b0f742/hoomd/box.py#L399-L410

## Proposed solution

Questions:
1. Should both `lattice_vectors` and `matrix` exist? (If not, I would remove `lattice_vectors` and keep `matrix`.)
2. Should the implementation(s) use C++ or pure Python? (I would prefer to keep everything in C++ if possible, which may be best to do by adding a method or two that handles this functionality in C++.)
3. If `lattice_vectors` is kept, should it be settable? (I think that it should match the settable nature of `matrix`, but as a lower triangular matrix since it is transposed.)

## Additional context

For another example, the freud library provides a `to_matrix()` method and provides lattice vectors individually as properties `v1`, `v2`, `v3`.

## Developer

I am willing to help with this if maintainers can offer guidance on the questions above.

**Comment by joaander** [comment]
Based on your description, I would remove `lattice_vectors` in favor of `matrix`. @b-butler should comment as well because he designed this API.

**Comment by b-butler** [comment]
I am fine with removing `lattice_vectors` in favor of `matrix`; however, I am not sure if moving the logic to C++ is necessary as some of the checks would be more cumbersome in C++ like checking that the array is upper-triangular. 

The API was originally designed after `freud`'s at the time of writing with a few differences. If we are already going to do this change should we use `to_matrix` and `from_matrix` rather than the property API while we are at it? Also, should we expose the lattice vectors as `v1,  v2, v3`?

**Comment by bdice** [comment]
My intentions in moving logic to C++ would be to ensure that all math operations are performed in only one place, to avoid possible loss of precision and avoid duplication in the code. It would be fine to sanitize inputs (like making sure the input matrix is upper triangular) in Python. Of course, if it is too difficult, the current split implementation between C++/Python is probably fine.

I like `to_matrix` and `from_matrix` (as a class method), and removing the matrix setter. I don't think exposing the lattice vectors is very useful but we could do it for consistency with freud if you like that.

**Comment by b-butler** [comment]
Okay, I am fine with that. @bdice, if you still are planning on implementing the changes we are trying to have a single beta version deprecation cycle (roughly speaking) so instead of removing methods could you raise a deprecation warning and keep the functionality for now with a note on when we are to remove the functionality (a # comment is fine, we aren't using a deprecation package currently).

Also, I am fine with the logic being in C++; I just thing some of the validation is much simpler in Python (by simpler I mean someone else wrote it :smiley:).

**Comment by bdice** [comment]
I welcome help from anyone who has time to make this change. I am currently prioritizing some other software cleanup projects.

**Comment by joaander** [comment]
@b-butler, you wrote the Box code, can you implement the fix for this?

**Comment by b-butler** [comment]
@joaander I am working on it.
