### ISSUE TITLE
Support systems with arbitrary scale

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1147]
## Description

Users should be able to use a system of units with any scale in HOOMD (e.g. use SI units for nanoscale systems or nanometer units for macro scale systems).

This request spawned from a discussion on #1141.

## Proposed solution

To make this possible, we need to replace absolute checks with relative checks where possible. Where not possible, we need to remove default values that are provided in units and require that users provide the values.

## Additional context

I have identified the following places that need to be modified. There may be others:

* Neighbor list `buffer` (current default is 0.4 [length])
    * Replace with `buffer_fraction` and set `buffer = max(r_cut) * buffer_fraction` each time the nlist is computed.
    * I'm not really pleased with this solution because the buffer distance is not really related to r_cut, but to the distance particles typically travel in a frame. However, the neighbor list has no idea about typical particle velocities or the value of `\delta t`.
    * An alternative would be to keep buffer and its default value, but limit its value to `buffer = min(buffer, 2*max(r_cut))`. This would prevent the neighbor list from setting a box spanning interaction size when the box size is small relative to the default buffer of 0.4. 
* Tolerances in FIRE.
    * Remove the default values and ask users to provide values.
* `I.x,I.y,I.z <= / > EPSILON` checks.
    * No need for EPSILON here, replace with 0. Users explicitly set `I.x = 0` exactly for axes that have no moment of inertia.
* Absolute tolerance checks in some HPMC overlap tests.
    * Set the tolerance to the existing tolerance multiplied the diameter of the particle.
    * ShapePolyhedron already does this.
    * ShapeSimplePolygon and XenoCollide need to be updated.

## Developer

Any developer is welcome to work on this. Please comment on this issue if you have any questions.

**Comment by mphoward** [comment]
I think that the neighbor list buffer should stay as a length rather than a fraction. Its optimal value is not really related the cutoff, and I would not want to need to adjust this fraction if the maximum cutoff in the system changed.

In my opinion, it does not make sense for this parameter to have a default value. The current default _was_ a good choice for a standard LJ liquid on a GPU ~10 years ago, but in MD, the optimal value buffer width depends a lot on temperature, density, cutoff, integration scheme (e.g., NVT vs. Brownian dynamics), and hardware. These considerations apply even in nicely chosen units, let alone if somebody wants to use another system of units. I rarely leave this value at the default myself, as I have tuned values that work nicely for the types of potentials I usually use.

Hence, I would vote to remove the default buffer value and require the user to choose it explicitly when constructing the neighbor list.

**Comment by joaander** [comment]
Yes, removing the default for `buffer` is a good solution. I worry that the vast majority of users just accept the default and are not even aware the parameter exists. However, being cynical, if we add `buffer=0.4` to the MD tutorial, most users will copy it without thinking - so this really isn't a change.

In either case, we'll also need to add a how to tutorial on choosing the right value.

**Comment by mphoward** [comment]
> I worry that the vast majority of users just accept the default and are not even aware the parameter exists.

^^ This is definitely true in my experience.
