### ISSUE TITLE
Compiling with NVHPC SDK and scaling on 8xA100 Delta platform with NVSwitch

### ISSUE THREAD

**Issue by vvsteg** [glotzerlab/hoomd-blue#1197]
I am trying to find the best way to run HOOMD on the DGX A100 like server with 8 GPU connected with NVSwitch.

Using NVHPC SDK I could not configure HOOMD with cmake (ver. 3.21.3). As far as I understand, cmake does not understand the nvc++ compiler.

```
cmake -DENABLE_GPU=on -DENABLE_MPI=on ../
-- The C compiler identification is NVHPC 21.9.0
-- The CXX compiler identification is NVHPC 21.9.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/software/nvidia/hpc_sdk/v21.9/Linux_x86_64/21.9/compilers/bin/nvc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/software/nvidia/hpc_sdk/v21.9/Linux_x86_64/21.9/compilers/bin/nvc++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring HOOMD v3.0.0-beta.12-2-ged60448
-- Setting build type to 'Release' as none was specified.
-- The CUDA compiler identification is NVIDIA 11.4.100
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /opt/software/nvidia/hpc_sdk/v21.9/Linux_x86_64/21.9/compilers/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
CMake Error at /opt/software/cmake/v3.21.3/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  REQUIRED_CUDA_LIB_VARS (missing: CUDA_cudart_LIBRARY CUDA_cudadevrt_LIBRARY
  CUDA_cufft_LIBRARY CUDA_nvToolsExt_LIBRARY CUDA_cusolver_LIBRARY
  CUDA_cusparse_LIBRARY)
Call Stack (most recent call first):
  /opt/software/cmake/v3.21.3/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  CMake/hoomd/FindCUDALibs.cmake:330 (find_package_handle_standard_args)
  CMake/hoomd/HOOMDHIPSetup.cmake:139 (find_package)
  CMakeLists.txt:107 (include)


-- Configuring incomplete, errors occurred!
```

Therefore, I have built HOOMD without MPI (with `-DENABLE_GPU=on` only).

However, the benchmarks show that scaling to 8 GPU is not very good. Here are the results for 4 million LJ particles (50000 steps):

1 GPU: 1096 sec
2 GPU: 695 sec
4 GPU: 547 sec
6 GPU: 428 sec
8 GPU: 348 sec

Is it possible that the CUDA-aware MPI built of HOOMD would provide better scaling? 
Is there a benefit of finding the way to build an MPI version of HOOMD for this system?

**Comment by joaander** [comment]
I am not familiar with the `nvc++` compiler, its features, or whether CMake supports it. The documentation details the compiler and MPI environments that we explicitly test: https://hoomd-blue.readthedocs.io/en/latest/building.html#install-prerequisites . You should use the native compiler `gcc` or `clang` and let CMake find the MPI libraries itself rather than using a wrapper compiler to build HOOMD with -DENABLE_MPI=on.

The CUDA aware MPI code path is not well maintained and has rarely if ever offered better performance over plain MPI.

I cannot guess whether MPI simulations will scale better than the unified memory implementation on your system. That is something you will need to benchmark and test. Regardless, A100 GPUs are very dense and Lennard-Jones is not computationally intensive so strong scaling will never be very efficient for this system.

In the future, submit support requests to the hoomd-users mailing list. This issue tracker is for bugs and feature requests.

**Comment by vvsteg** [comment]
Continued in https://groups.google.com/g/hoomd-users/c/OkOeCVABvi8/m/tjN83BVjBAAJ
