### ISSUE TITLE
Support cereal 1.3.1

### ISSUE THREAD

**Issue by yurivict** [glotzerlab/hoomd-blue#1204]
```
ld: error: unable to find library -lcereal
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is despite cereal providing cmake files.

cereal-1.3.0.10
Version: 3.0.0-beta.13
OS: FreeBSD 13

**Comment by joaander** [comment]
Cereal is not a shared library, it is a header file. HOOMD-blue uses `find_package` to utilize the CMake configuration file provided by the cereal library. Ensure that your system installs cereal's CMake configuration file correctly.

**Comment by yurivict** [comment]
cereal installs these files:
```
	/usr/local/lib/cmake/cereal/cerealConfig.cmake
	/usr/local/lib/cmake/cereal/cerealConfigVersion.cmake
	/usr/local/lib/cmake/cereal/cerealTargets.cmake
```

I think hoomd-blue doesn't use returned values correctly.

**Comment by joaander** [comment]
HOOMD-blue uses the cereal CMake configuration correctly:
https://cmake.org/cmake/help/v3.22/manual/cmake-packages.7.html
https://github.com/glotzerlab/hoomd-blue/blob/52bbbb5202ad73c576a83b47633d15f3b052af77/CMake/hoomd/HOOMDMPISetup.cmake#L8-L11
https://github.com/glotzerlab/hoomd-blue/blob/52bbbb5202ad73c576a83b47633d15f3b052af77/hoomd/CMakeLists.txt#L339-L341
https://github.com/USCiLab/cereal/blob/02eace19a99ce3cd564ca4e379753d69af08c2c8/CMakeLists.txt#L49-L60

You don't provide the output from the `cmake` configure step, so I have no way to know if your configuration is using `/usr/local/lib/cmake/cereal/cerealConfig.cmake` or not.

**Comment by yurivict** [comment]
[Here](https://people.freebsd.org/~yuri/hoomd-blue-3.0.0-beta.13.log) is the complete build log.

**Comment by yurivict** [comment]
[Here](https://people.freebsd.org/~yuri/cereal-cmake-files.tgz)  are all cereal's cmake files.

**Comment by joaander** [comment]
Thanks, your upload confirms that this is an issue with the cereal installation. Your `cerealTargets.cmake` defines the target as `cereal::cereal`, not `cereal` as the library installs from the source. This is not a but in HOOMD-blue. If FreeBSD patches the cereal installation, it will also need to patch HOOMD-blue accordingly.

**Comment by yurivict** [comment]
No, the FreeBSD port doesn't patch cereal.
The files I've sent you were installed by cereal-1.3.0-10-g64f50dbd
But I just checked, hoomd-blue has the same problem with cereal-1.3.1

Do you think that cereal has a bug in their cmake files?

**Comment by joaander** [comment]
cereal 1.3.0 creates only the `cereal` target: https://github.com/USCiLab/cereal/blob/02eace19a99ce3cd564ca4e379753d69af08c2c8/CMakeLists.txt#L49-L60
This is the target I find on all platforms I have tested (Ubuntu, Arch Linux, conda-forge, and others).

cereal 1.3.1 significantly rewrites the CMake scripts and adds the `cereal::cereal` target, though keeping the `cereal` target for backwards compatibility with previous versions: https://github.com/USCiLab/cereal/blob/1de8fe89471d69ea392ea260ce74e079d5f4b415/CMakeLists.txt#L58-L99

I checked and the `cereal` target unfortunately does not appear in the 1.3.1 `cerealTargets.cmake`. However, you reported that you installed cereal 1.3.0 in the original bug report - so I don't understand the behavior you are seeing.

I can attempt to add a workaround to HOOMD-blue's CMake config for cereal 1.3.1. The root cause is with the breaking changes made in `cereal` 1.3.0 -> 1.3.1 and not anything incorrect in HOOMD-blue's CMake scripts.

**Comment by yurivict** [comment]
Since cereal has just released 1.3.1 you probably should support both for a while.

**Comment by yurivict** [comment]
> However, you reported that you installed cereal 1.3.0 in the original bug report - so I don't understand the behavior you are seeing.

The original report was for ```cereal-1.3.0.10``` which is an intermediate revision that happened to be used on FreeBSD. "10" is generated by git for such revisions.

**Comment by joaander** [comment]
#1206 should fix this.

**Comment by yurivict** [comment]
This fixed the problem. Thank you!
