### ISSUE TITLE
Implementing Protracted Colored Noise Dynamics

### ISSUE THREAD

**Issue by jbdelony** [glotzerlab/hoomd-blue#1219]
## Description

I am looking to implement protracted colored noise dynamics (PCND) as a publishable contribution in HOOMD-blue.  PCND is a method that adds stochastic noise in order to increase the local phase space sampling in a similar fashion to Brownian or Langevin dynamics.  This technique has been applied to both [linear polymer systems](https://doi.org/10.1002/mats.201700062) and [polymer grafted nano-particles](https://doi.org/10.1016/j.commatsci.2019.05.030) in 2019 and [2020](https://doi.org/10.1021/acs.macromol.0c00981).

## Proposed solution

This technique is currently implemented in HOOMD-blue v2.x via [hard-coded modifications](https://github.com/USF-GT-Molecular-Modeling/PCND) to the deprecated `cgcmm` module.  The user would pass in the desired `tau` (correlation time) and `Xi` (RMS force magnitude) parameters to PCND, which is implemented as an additional angle term.  In polymer systems, the force due to PCND is applied to the center bead of an angle oriented along the backbone of the chain in order to bias toward polymer reptation.  In the case of polymer grafted nano-particles, the force can either be applied to the whole body or the polymer arms.

## Additional context

Attached is the output of `diff hoomd-blue/hoomd/cgcmm/ PCND-Nanoparticles-master/hoomd/cgcmm/` to highlight the edits made to the existing `cgcmm` module (as compared to the latest v2.9 branch).  This feature is primarily implemented in `CGCMMAngleForceGPU.cu`.
[HOOMD_full_diffs.txt](https://github.com/glotzerlab/hoomd-blue/files/7996750/HOOMD_full_diffs.txt)

## Developer

I plan to be the primary contributor along with collaborators at Georgia Tech, but I need guidance from the HOOMD-blue developers as to how this functionality can be cleanly implemented and published in v3.0.

**Comment by joaander** [comment]
I deprecated CGCMM in v2 and removed it in v3. As far as I know, no one but the original authors used the code. I am not familiar enough with the details of the CGCMM angle implementation to understand your diff.

Does the PCND method have general applications to a wide base of HOOMD-blue users? If not, you should consider maintaining the method as an external plugin.

**Comment by jbdelony** [comment]
Yes, PCND could be applied to any system in which a significant energetic barrier must be overcome to reach an equilibrium state that is impractical to reach through MD alone.  Because the stochastic noise applied is spatially correlated along the bodies of interest, it can increase the sampling of the relevant diffusive modes of that system (e.g., correlated fluctuations can be applied along the backbone of a polymer chain to enhance reptation).  It has been used to equilibrate LJ glasses, anneal diblock copolymer films with kinetically trapped defects, and assemble nanoparticle systems.

We have not used PCND in these specific applications yet, but we also intend to implement it for modeling glassy aging in homopolymer systems and relaxing polymer films containing chains above the entanglement weight.  I know it is of interest to the Henderson and Simmons groups at USF, the Ludovice group at Georgia Tech, and the Peters group at Louisiana Tech.

Given the wide range of potential applications, would you be interested in adding PCND to the code base if I submit a PR?

**Comment by joaander** [comment]
I would welcome a pull request for review. All pull requests are reviewed to ensure that the code is implemented cleanly and follows the standards set by the codebase. Feel free to reach out to me via e-mail if you have questions on the implementation details before starting work on a pull request off the master branch.

From looking at your diff, I have some questions. It appears that PCND is a single force compute that uses the angle potential data structures to apply forces on the central particle in the angle. Is that correct? How can this help in systems like LJ glasses and nanoparticle self-assembly where there are no angle potentials? Is the angle potential really the best choice for this? Does it support MPI and GPU execution?

I also see that you use `curand`. HOOMD uses random123 for random number generation to compute random numbers when needed instead of storing them - see `RandomNumbers.h`. We have also removed all use of `cudaBindTexture` and the timestep counter is now 64-bit.
