### ISSUE TITLE
How to broadcast values in mpi when running hoomd?

### ISSUE THREAD

**Issue by zhangyemayapro** [glotzerlab/hoomd-blue#1239]
## Description
I have a value  which is only generate in rank 0
What can I do wo broadcast  to value to other rank?
----
a=1 in rank 0
how can rank 1 get the a value?
thanks for your help~

**Comment by zhangyemayapro** [comment]
My  hoomd is stable version

**Comment by joaander** [comment]
This is not a task to complete for HOOMD-blue development. Please direct support questions to the mailing list.

HOOMD-blue internally broadcasts all values that it needs to in order to operate. If you wish to broadcast values between MPI ranks in your python script, you should use a library such as `mpi4py`. HOOMD (both v2 and v3) interoperate with mpi4py communicators.

**Comment by zhangyemayapro** [comment]
thanks for your help~
