### ISSUE TITLE
Add MD integration with movement limit support.

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1261]
## Description

Integration methods with limits on the absolute movement of particles can be useful when relaxing high energy states.

## Proposed solution

Add a new integration method class (or classes) that implements the limit.

## Additional context

While the Python interface will provide this as a separate class to clarity, the C++ implementation will add the option to the existing class to prevent code duplication.

## Developer

Seeking interested developers.

**Comment by joaander** [comment]
Expose this for the NVE integrator (C++ already supports the limit). My first idea for a class name is `DisplacementLimitedNewtonian`. Open to suggestions for improvement.

**Comment by tommy-waltmann** [comment]
For a name, why not use `DisplacementLimitedNVE`? I think that would make it clearer that the new class is exactly the same as the old NVE with a displacement limit.

Also, having separate classes in python for this seems a little clunky to me because it creates asymmetry between python and C++. Why not have the python side of this mirror the C++ side, and just add an option to limit the particle movement in the NVE that is already there?

**Comment by joaander** [comment]
If you limit the particle movement, then it is no longer a constant energy (NVE) ensemble. Including NVE anywhere in the name is a misnomer.

**Comment by b-butler** [comment]
@tommy-waltmann we do this in the `NPT` and `NPH` methods as well. I think the asymmetry is warranted as they are fundamentally two different equations of motion.
