### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by MartinGirard** [glotzerlab/hoomd-blue#1439]
### Description

There is a strong push in the EU community to have data that is so-called FAIR -- findable, accessible, interoperable and reusable. In Germany, the push is institutional; the DFG best practices already hints toward this (see [DFG guidelines on handling data](https://www.dfg.de/download/pdf/foerderung/grundlagen_dfg_foerderung/forschungsdaten/guidelines_research_data.pdf)). This has now expanded towards MD simulations, through the FAIRMat consortium funded by the DFG through national data infrastructure funds (NFDI). It will likely become mandatory in a not so far future.

To be compliant with FAIR principles, we need to supply metadata along with simulation data. This means information such as which integrators were used, timestep and force-field information should be available. Ideally, this should also include thermodynamic data such as potential energy, temperature, etc. Obviously these values may change over time, e.g. during temperature ramps, and this should probably be a "metadata trajectory". 

### Proposed solution

I would propose to embed, by default, metadata in a tree structure (e.g. json) in the trajectory. This can be done by adding a metadata section in the gsd file, and populating it by going through all attached objects in hoomd during write. This ensures that we do not need much serialization, e.g. of Variant objects.

Implementation issues that I already see:

- Triggered objects (e.g. updaters) would need some level of serialization since they're not called at every timestep
- Python actions acting on the simulation would need to be somehow described, at the very least by noting that there is one. Ideally, by including the python function used if we can
- FAIRmat proposes to search by thermodynamic ensemble, which would require a complex series of overloads based on integrators. This is further complicated by potential presence of multiple integrators and DPD thermostatting. NPH integration with DPD is NPT. Two NVT thermostats with the same temperatures is NVT, but two thermostats with different temperatures is non-equilibrium.  Is there a general solution?

At some level, the user is responsible if he is using non-standard things. Our responsibility would be to generate the "best" metadata we can. 

### Additional context

The initial plan of FAIRMat was to start with commonly used package (gromacs & lammps) and parse the relevant files. They internally store their information in json files. I've attached an example of a parsed gromacs simulation. 

[GromacsSimulation.json.zip](https://github.com/glotzerlab/hoomd-blue/files/10066232/GromacsSimulation.json.zip)

FAIRMat does not really make a difference between simulation data and metadata. In this json file, there is therefore things such as run[]->system[]->atoms, which contain trajectory information (positions, velocities, etc.). Some of the other relevant information in there:

- run->system->atom_groups, which contains topology information (which I guess could be parsed from bonds)
- run->calculation: observables, which includes some per-particle info (e.g. forces) and thermodynamic data (such as pressure)
- run->method->force_field: which has some topology information (bonds & bonded FF), and should include non-bonded force-fields
- workflow->molecular_dynamics->integration_parameters: thermostats and parameters
- workflow->molecular_dynamics->results: basic analysis results from post-processing on FAIRMat side, whcih can then be visualized on their GUI

While we could technically directly export into their internal json structure, I'm not sure it is the right solution. There is also currently no metadata standard for MD.

**Comment by JFRudzinski** [comment]
I am the FAIRmat representative / domain expert for soft matter simulations, and can be contacted with any questions regarding FAIRmat's motivation, approach, etc. 

I couple things to initially note:
The goal of the FAIRmat project is to provide infrastructure in the form of a repository and associated tools for storing, sharing, and repurposing materials data (see https://nomad-lab.eu/). Although our initial approach with MD simulations was to parse the standard output of commonly used codes (as mentioned by Martin), future support for other (more flexible) software is imagined to happen in collaboration with code developers.

The example provided by Martin above represents our current (very preliminary) approach to the MD metadata. While some aspects of the structure are fixed by our infrastructure requirements, the creation of data structures to accurately and efficiently describe MD simulations is very much a work in progress. So, again, we are looking for opportunities to collaborate with code developers to incorporate relevant metadata / data structures into our infrastructure.

**Comment by joaander** [comment]
Some of this information is already available:
* Topology information - included in the GSD trajectory following the GSD specification.
* Instantaneous thermodynamic quantities (potential energy, kinetic temperature, virial pressure, ...) - https://hoomd-blue.readthedocs.io/en/v3.6.0/module-md-compute.html#hoomd.md.compute.ThermodynamicQuantities
* Per particle forces: https://hoomd-blue.readthedocs.io/en/v3.6.0/module-md-force.html#hoomd.md.force.Force.forces

By design, very little of this is written by default. HOOMD-blue is a Python API for executing simulations. Users make API calls to choose what output they would like and is relevant to their simulation. We can provide examples in the documentation and/or a helper function to add the loggables that FAIRMat expects.

The following information is not readily available. As @MartinGirard suggests, we can add a json object to the GSD trajectory that represents the simulation metadata, including:
* Schema version
* HOOMD version
* Compilation flags
* Device description
* The simulation operations and their parameters
  * Updaters
  * Integrator (including the step size)
    * Forces (and non-bonded and bonded force field parameters)
    * Integration methods (including temperature and/or pressure set points)
* Unit system

From this information, FAIRmat can infer the ensemble (per the heuristics @MartinGirard suggests) and extract the parameters of interest. Writers, computes, and tuners do not impact the simulation run, so we do not need to include them.

@JFRudzinski how does FAIRmat track the units of the quantities stored? HOOMD-blue operates with self-consistent units and different users are free to choose any set they like (https://hoomd-blue.readthedocs.io/en/v3.6.0/units.html). Some users might choose the standard AKMA or MD unit sets, some might use SI, and many users may not even determine a mapping to a real set of units. There is no functional way that HOOMD-blue itself can provide details on the units to FAIRmat, though we can provide some mechanism for the user to pass through a description of their unit system.

**Comment by joaander** [comment]
Also: for custom operations defined in Python or via plugins, the best we can do is to record the name of the class. Pickling the object or otherwise capturing its code for storage in a database creates a number of security vulnerabilities.

**Comment by JFRudzinski** [comment]
@joaander : Thanks for the quick response and very useful information. 

Units - At the moment the FAIRmat infrastructure only supports physical units. This is determined by reading the log or other outputs files of the calculation/simulation software which typically either explicitly contains this information, or at least contains an input parameter which defines the choice of some standard unit system. I have already opened an issue for creating support for reduced units. Storing some sort of mapping to physical units is an interesting idea, I will bring this into the unit discussion in the future as well.

**Comment by JFRudzinski** [comment]
> Also: for custom operations defined in Python or via plugins, the best we can do is to record the name of the class. Pickling the object or otherwise capturing its code for storage in a database creates a number of security vulnerabilities.

Yes, this is completely understood. I would say that at least for the foreseeable future "precise reproducibility" is not our main target (exactly because of such difficulties). Instead, we are focused on documenting important overarching descriptions of the simulations such that other researchers can access and assess what has been done, and then re-use the data without becoming an expert in the underlying software. As the methodology considered becomes more complex (e.g., very exotic simulation workflows), the onus falls on the user to accurately document what they have done. The developers of the simulation software and storage infrastructure can only try to provide tools for performing this documentation effectively. (I think this is more or less in line with your philosophy as stated above).
