### ISSUE TITLE
Custom per-particle quantities.

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1533]
### Description

C++ plugin developers would appreciate the ability to dynamically register new per-particle quantities. These would be registered at run time, sorted, communicated over MPI, and (possibly) written to GSD files.

This would replace the need for plugin developers to abuse existing properties (like `diameter` #1266).

### Proposed solution

I have no proposal at this time. Any implementation should allow the registration of an arbitrary number of per-particle scalar and/or 2,3, or 4-vector quantities identified by a user-defined string.

### Additional context

Once this feature is implemented, remove `diameter` as it is no longer needed: See #1266.

**Comment by mphoward** [comment]
I had thought about doing something like this a long time ago. The best solution I came up with was to majorly refactor the `Communicator` so that `ParticleData` was communicated by a similar mechanism, rather than packing stuff into a special struct. But this felt like a lot of work given the way the MPI code is organized, so I stopped there.

**Comment by joaander** [comment]
Yes, this would be a time-consuming task. I have no immediate plans to work on it.
