### ISSUE TITLE
Fix compiler warnings in MPCD

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#1844]
### Description

When compiling HOOMD-blue 4.8.0 with CUDA 12.5, I get the following warnings:
```
[623/1053] Building CUDA object hoomd/mpcd/CMakeFiles/_mpcd.dir/SRDCollisionMethodGPU.cu.o
ptxas warning : Stack size for entry function '_ZN5hoomd4mpcd3gpu6kernel16srd_draw_vectorsILb1EEEvP7double3PdPKS4_NS_7Index3DE4int35uint3S9_mtdjj' cannot be statically determined
ptxas warning : Stack size for entry function '_ZN5hoomd4mpcd3gpu6kernel16srd_draw_vectorsILb1EEEvP7double3PdPKS4_NS_7Index3DE4int35uint3S9_mtdjj' cannot be statically determined
ptxas warning : Stack size for entry function '_ZN5hoomd4mpcd3gpu6kernel16srd_draw_vectorsILb1EEEvP7double3PdPKS4_NS_7Index3DE4int35uint3S9_mtdjj' cannot be statically determined
```

### Motivation and context

@mphoward I thought these warnings would go away with the mpcd rewrite as it moved away from virtual functions. Is it possible to compile without these warnings?

**Comment by mphoward** [comment]
I’ve seen those in some of my builds (with older CUDA versions), but I assumed they were something weird with my setup because I didn’t know what would cause that issue. I’ll investigate.

**Comment by joaander** [comment]
I assumed (without verification) that this was due to the prior usage of virtual on the GPU. It may be caused by something else.

**Comment by mphoward** [comment]
That kernel never used any virtual methods, and I didn't really do much to it when I ported to v4, so I'm a little confused there... the demangled name is:
```
void hoomd::mpcd::gpu::kernel::srd_draw_vectors<true>(double3*, double*, double3 const*, hoomd::Index3D, int3, uint3, hoomd::Index3D, unsigned long, unsigned short, double, unsigned int, unsigned int)
```
Both the false and true templates are generated by the driver function, so the warning must be coming from something that's only on the true path.

**Comment by mphoward** [comment]
I think this is caused by the `GammaDistribution`. iirc, I implemented that distribution with the assumption `alpha > 1`, which is always true for how MPCD uses it:

https://github.com/glotzerlab/hoomd-blue/blob/68225e7b6eec8003a918084e24bd835c5a50d24c/hoomd/mpcd/SRDCollisionMethodGPU.cu#L79-L86

This assumption was relaxed for the Bussi thermostat in this commit:

https://github.com/glotzerlab/hoomd-blue/commit/c9ac75fdb03a4e3063bbe42feac4efb5661272a1

This will use either 0 or 1 level of recursion depending on `alpha`, and since `alpha` is dynamic, nvcc can't determine the stack size for the kernel. The Bussi thermostat is the only other spot `GammaDistribution` is used, but that is CPU only.

To fix it, we can rearrange `GammaDistribution::operator()` to remove the recursion. I will try this.
