### ISSUE TITLE
Backport communicator optimizations

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#249]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/249) by me.**

----------------------------------------

Consider backporting communicator optimizations from pull request #342

**Comment by joaander** [comment]
@mphoward @jglaser Are we still planning to backport communicator optmizations from MPCD to the core? If not, feel free to close as wontfix.

**Comment by mphoward** [comment]
I think that depends on how you all feel about the MPI code paths on the CPU and also what the bottlenecks are there. In MPCD, particle migration had a huge bottleneck because there were unnecessary loops through millions of particles, and so I was able to save alot of cycles with those optimizations. But, if migration is only a small fraction of your MD time in MPI, then it probably isn't worth it because the number of particles per rank is much smaller in MD.
