### ISSUE TITLE
Replace Saru with random123

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#261]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/261) by me.**

----------------------------------------

HOOMD's use of the Saru RNG is sporadic and inconsistent. Pull request #359 goes a long way toward making it better, but it doesn't solve the fundamental issue that Saru is not absolutely reliable and that it only has three seeds.

We should rewrite using random123 which is much more thoroughly tested and reliable. The philox 4x32 generator takes in 6 seeds. This should more than serve our needs in HOOMD without needing to resort to combining seeds (i.e. timestep+seed).

1. rng id
2. tag
3. step
4. user seed
5. rank
6. counter

tag, step, and rank may vary based on specific uses in the hoomd code (not all uses have all of these).

We should give different RNGs (i.e. langevin, HPMC grid shift, etc...) constants collected in a  header file so that it is straightforward to assign a new unique constant to a RNG.

One issue with the random123 API is that it is very low level and not trivially expandable to float and double. Since HOOMD already uses the Saru API, I propose that we re-implement  the parts of the Saru API that we use as a thin wrapper around random123. This API would maintain an internal counter to get different random numbers following Saru's stream concept - and it can generate as many as it needs. 

Since gaussian random values are commonly needed, we can also add an API for requesting these. Vectors are also a common requirement. An API to return a random vector is useful for performance as well, because random123 philox 4x32 generates 4 32 bit values with one call to the RNG.

**Comment by mphoward** [comment]
I found another possible bug related to Saru. Using the three-seed hash `(309, 1313, 42)` to draw a float returns a value that is machine-identical to 1.0f:
```
hoomd::detail::Saru rng(309, 1313, 42);
rng.f() == 1.0f
```
This conflicts with the documentation that advertises a value lying in [0,1) and causes issues when the value is assumed to lie in a certain range (e.g., passing 1.0f - rng.f() to a log).

Rather than try to fix this, I am going to reject these endpoint values in my code. I hope that this revamp can maybe get some traction to fix possible issues like this, as these sorts of bugs are exceedingly difficult to track down. When I was looking at the Saru code, I was also reminded that the uniform double is drawn in a pretty lazy way (not using two true random ints), and so this is also suboptimal. Plus, it is very difficult to properly unit test the generator, and so it would be better to be using something that can really be trusted.
