### ISSUE TITLE
Remove compute 3.0 optimizations

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#330]
**[Original report](https://bitbucket.org/glotzer/hoomd-blue/issue/330) by me.**

----------------------------------------

We can drastically simplify kernel launching code in hoomd by removing support for compute 3.0 optimizations (textures). CUB has an API for accessing data types with specific cache load modifies that we can consider using, otherwise we can use __ldg directly.

**Comment by bdice** [comment]
This issue is almost purely a removal of code. These old devices with compute 3.0 are not tested. Resolving this issue involves removing all instances of code like `#if (__CUDA_ARCH__ >= 300)`, particularly instances like in `texFetchScalar4` where the `tex_ref` argument is no longer necessary and refactoring accordingly.
