### ISSUE TITLE
Can we install hoomd-blue in windows environment?

### ISSUE THREAD

**Issue by geekonloose** [glotzerlab/hoomd-blue#346]
Sorry, this is not any bug submission. 

I was trying to install hoomd-blue in windows 10 through conda. But it was throwing error that package is not available in conda-forge. Later, I learned that, it is only available for Linux and mac. Is there way out to install in windows?

**Comment by joaander** [comment]
The current version of HOOMD-blue does not support native windows builds. Some users have had success installing HOOMD in the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

Supporting native builds of HOOMD on Windows would require a dedicated and experienced Windows developer to work closely with the lead developers in order to add support for Windows with a minimum of changes to the code.  Said developer would also need to be available for ongoing user support and testing on Windows platforms. Any interested developers, please contact me.

This issue tracker is used for bug reports and feature requests. General user support questions are best asked on the [hoomd-users mailing list](https://groups.google.com/forum/#!forum/hoomd-users) where a large, active, and experienced community can respond to questions.

**Comment by geekonloose** [comment]
Thank you for letting us know. And apologies, I didn't knew about hoomd-users mailing list.

**Comment by joaander** [comment]
No worries, the README doesn't even mention what platforms HOOMD supports or the existence of the user community. These are only documented on the projects home page and in the reference documentation. I opened #348 to remind us that this information should be more visible.
