### ISSUE TITLE
hpmc plug-in doesn't get compile

### ISSUE THREAD

**Issue by hanyunfan** [glotzerlab/hoomd-blue#353]
1. Error message:

  File "bmark.py", line 4, in <module>
    from hoomd import hpmc
**ImportError: cannot import name hpmc**

2. Compiling parameters:

export SOFTWARE_ROOT=/mnt/lustrefs/frank/hoomd/v2.5.0

rm -rf build75; mkdir build75; cd build75
cmake3 ../ -DCMAKE_INSTALL_PREFIX=${SOFTWARE_ROOT}/sm75-single -DENABLE_MPI=ON -DENABLE_CUDA=ON -DENABLE_MPI_CUDA=ON -DCUDA_ARCH_LIST=70 -DPYTHON_EXECUTABLE=/usr/bin/python -DSINGLE_PRECISION=ON **-DBUILD_HPMC=ON**

make -j20 install

3. CMakeCache file does show BUILD_HPMC is on:

[frank@gpu032 build75]$ grep HPMC CMakeCache.txt
BUILD_HPMC:BOOL=ON
//Enable mixed precision computations in HPMC
ENABLE_HPMC_MIXED_PRECISION:BOOL=ON

4. But there is no hpmc directory at all after successful compiling.

[frank@gpu032 hoomd]$ ll
total 10432
-rw-r--r-- 1 frank internalusers   26668 Feb  5 19:59 analyze.py
-rw-r--r-- 1 frank internalusers   26085 Feb 27 13:21 analyze.pyc
-rw-r--r-- 1 frank internalusers    1412 Feb  5 19:59 benchmark.py
-rw-r--r-- 1 frank internalusers    1480 Feb 27 13:21 benchmark.pyc
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:19 cgcmm
-rw-r--r-- 1 frank internalusers   17982 Feb  5 19:59 cite.py
-rw-r--r-- 1 frank internalusers   11031 Feb 27 13:21 cite.pyc
drwxr-xr-x 3 frank internalusers    4096 Feb 27 13:19 CMake
-rw-r--r-- 1 frank internalusers    2872 Feb  5 19:59 CMake_build_options.cmake
-rw-r--r-- 1 frank internalusers     393 Feb  5 19:59 CMake_install_options.cmake
-rw-r--r-- 1 frank internalusers    1102 Feb  5 19:59 CMake_preprocessor_flags.cmake
-rw-r--r-- 1 frank internalusers     424 Feb  5 19:59 CMake_src_setup.cmake
-rw-r--r-- 1 frank internalusers    1075 Feb  5 19:59 CMake_version_options.cmake
-rw-r--r-- 1 frank internalusers   13604 Feb  5 19:59 comm.py
-rw-r--r-- 1 frank internalusers   11538 Feb 27 13:21 comm.pyc
-rw-r--r-- 1 frank internalusers   11742 Feb  5 19:59 compute.py
-rw-r--r-- 1 frank internalusers   11023 Feb 27 13:21 compute.pyc
-rw-r--r-- 1 frank internalusers   15657 Feb  5 19:59 context.py
-rw-r--r-- 1 frank internalusers   14262 Feb 27 13:21 context.pyc
-rw-r--r-- 1 frank internalusers   81513 Feb  5 19:59 data.py
-rw-r--r-- 1 frank internalusers   88723 Feb 27 13:21 data.pyc
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:19 dem
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:19 deprecated
-rw-r--r-- 1 frank internalusers   32135 Feb  5 19:59 dump.py
-rw-r--r-- 1 frank internalusers   28231 Feb 27 13:21 dump.pyc
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:19 example_plugin
-rw-r--r-- 1 frank internalusers    1496 Feb  5 19:59 FindGit.cmake
-rw-r--r-- 1 frank internalusers     410 Feb  5 19:59 Findlibgetar.cmake
-rw-r--r-- 1 frank internalusers     896 Feb  5 19:59 FindThrust.cmake
-rw-r--r-- 1 frank internalusers    3574 Feb  5 19:59 GetGitRevisionDescription.cmake
-rw-r--r-- 1 frank internalusers   23912 Feb  5 19:59 group.py
-rw-r--r-- 1 frank internalusers   22822 Feb 27 13:21 group.pyc
-rw-r--r-- 1 frank internalusers   15933 Feb  5 19:59 hdf5.py
-rw-r--r-- 1 frank internalusers    1571 Feb  5 19:59 HOOMDCFlagsSetup.cmake
-rw-r--r-- 1 frank internalusers    1784 Feb  5 19:59 HOOMDCommonLibsSetup.cmake
-rw-r--r-- 1 frank internalusers    3923 Feb  5 19:59 HOOMDCUDASetup.cmake
-rw-r--r-- 1 frank internalusers     491 Feb  5 19:59 HOOMDMacros.cmake
-rw-r--r-- 1 frank internalusers    2156 Feb  5 19:59 HOOMDMPISetup.cmake
-rw-r--r-- 1 frank internalusers     150 Feb  5 19:59 HOOMDNumpySetup.cmake
-rw-r--r-- 1 frank internalusers      76 Feb  5 19:59 HOOMDOSSpecificSetup.cmake
-rw-r--r-- 1 frank internalusers     576 Feb  5 19:59 HOOMDPythonSetup.cmake
-rwxr-xr-x 1 frank internalusers 9749192 Feb 27 13:17 _hoomd.so
drwxr-xr-x 4 frank internalusers    4096 Feb 27 13:19 include
-rw-r--r-- 1 frank internalusers   10468 Feb  5 19:59 __init__.py
-rw-r--r-- 1 frank internalusers   17778 Feb  5 19:59 init.py
-rw-r--r-- 1 frank internalusers   10640 Feb 27 13:21 __init__.pyc
-rw-r--r-- 1 frank internalusers   15505 Feb 27 13:21 init.pyc
-rw-r--r-- 1 frank internalusers   12026 Feb  5 19:59 integrate.py
-rw-r--r-- 1 frank internalusers    7806 Feb 27 13:21 integrate.pyc
-rw-r--r-- 1 frank internalusers   15816 Feb  5 19:59 lattice.py
-rw-r--r-- 1 frank internalusers   14615 Feb 27 13:21 lattice.pyc
-rwxr-xr-x 1 frank internalusers  102056 Feb 27 13:16 libquickhull.so
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:21 md
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:19 metal
-rw-r--r-- 1 frank internalusers    4638 Feb  5 19:59 meta.py
-rw-r--r-- 1 frank internalusers    5351 Feb 27 13:21 meta.pyc
drwxr-xr-x 2 frank internalusers    4096 Feb 27 13:19 mpcd
-rw-r--r-- 1 frank internalusers   12097 Feb  5 19:59 option.py
-rw-r--r-- 1 frank internalusers   10184 Feb 27 13:21 option.pyc
-rw-r--r-- 1 frank internalusers      44 Feb  5 19:59 test.cc
-rw-r--r-- 1 frank internalusers   21911 Feb  5 19:59 update.py
-rw-r--r-- 1 frank internalusers   20370 Feb 27 13:21 update.pyc
-rw-r--r-- 1 frank internalusers    5024 Feb  5 19:59 util.py
-rw-r--r-- 1 frank internalusers    5124 Feb 27 13:21 util.pyc
-rw-r--r-- 1 frank internalusers    5910 Feb  5 19:59 variant.py
-rw-r--r-- 1 frank internalusers    5352 Feb 27 13:21 variant.pyc
[frank@gpu032 hoomd]$ pwd
/mnt/lustrefs/frank/hoomd/v2.5.0/sm75-single/hoomd

**Comment by joaander** [comment]
HPMC **requires** `-DSINGLE_PRECISION=OFF`.

**Comment by hanyunfan** [comment]
Just found out if enable single precision, hpmc module will be turned off in cmake script. Does anyone know the reason? There even has an option in hpmc to build it in mixed precision. what's the reason hpmc cannot be compiled with single precision hoomd? why hpmc can be built with mixed precision when building hoomd with double precision?

**Comment by hanyunfan** [comment]
> HPMC **requires** `-DSINGLE_PRECISION=OFF`.

Thank you, do you know the reason? or any plan to enable HPMC with single precision?

**Comment by joaander** [comment]
> Does anyone know the reason?

Yes: floating point cancellation errors cause a loss of precision resulting in incorrect simulation results. Many of the unit and validation tests fail when you build HPMC with only single precision.

> There even has an option in hpmc to build it in mixed precision

Yes, this is the default. It provides all (or nearly all) of the performance of full single precision build, but produces correct results.

> why hpmc can be built with mixed precision when building hoomd with double precision?

Because the mixed precision mode uses double precision to store particle coordinates and single precision when performing overlap checks. Read more about this in our paper: https://doi.org/10.1016/j.cpc.2016.02.024

**Comment by hanyunfan** [comment]
I guess my questions are:

1) Can we have single precision hoomd + mixed precision HPMC?
2) Can we have mixed precision hoomd + mixed precision HPMC?

I am asking because there are GPUs really good with single and mixed precision, but not double precision. If either above case can be supported, we may see performance boost.

Thanks,
Frank

> Because the mixed precision mode uses double precision to store particle coordinates and single precision when performing overlap checks. Read more about this in our paper: https://doi.org/10.1016/j.cpc.2016.02.024

**Comment by joaander** [comment]
> 1. Can we have single precision hoomd + mixed precision HPMC?

No, this is not possible in a single build. HPMC and HOOMD MD use the same underlying data structures (particle coordinates, cell list, etc...). 

> 2. Can we have mixed precision hoomd + mixed precision HPMC?

This would be possible, yes. It would require a significant amount of development and testing effort. We have not prioritized that work because: a) most users of HOOMD run it on national super-computing centers where P100 and V100 GPUs are very fast at double precision. Many double vs single MD benchmarks on these GPUs only show a slight performance advantage to a full single precision build. Geforce gaming cards show a larger delta, and there are a few cases where single can vastly outperform double even on V100. b) In these cases, users that need both HPMC and MD simply maintain separate builds.

That being said, there is some work in this direction. @mphoward is working on a new neighborlist implementation that uses fixed precision AABB trees. It has the potential to be faster than the cell list based code path, in part because of the fixed precision representation.

We may find time in the future to fully implement the rest of a mixed precision MD engine. I opened #355 to track this. Contributions are welcome, but I would want to work very closely with any outside contributor working on this implementation to ensure it meets the quality, generality, and developer standards for the project.

**Comment by hanyunfan** [comment]
@joaander Thank you very much for those details. I am testing T4 cards and found it potentially could be beneficial from mixed precision for new HPC clusters. And all those single digits cards T4,P4 and M4 doesn't have storage FP64 FLOPS. And this series should have successors in future since this kind of card is designed for DL inference.

It would be good to leverage this hardware, and I'd like to help with testing/benchmarking the mixed precision code once it is available.
