### ISSUE TITLE
JIT is broken

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#358]
Recent changes regarding external field support in JIT introduced linker-level dependencies between the _jit and the _hpmc targets.

This simple script fails:
```
import hoomd
from hoomd import jit
from hoomd import hpmc
```

with the error message:
```
Traceback (most recent call last):
  File "twf.py", line 2, in <module>
    from hoomd import jit
  File "/nfs/turbo/bi-vislab/jsglaser/hoomd-install-dbl/hoomd/jit/__init__.py", line 17, in <module>
    from hoomd.jit import patch
  File "/nfs/turbo/bi-vislab/jsglaser/hoomd-install-dbl/hoomd/jit/patch.py", line 5, in <module>
    from hoomd.jit import _jit
ImportError: generic_type: type "ExternalFieldJITSphere" referenced unknown base type "hpmc::ExternalFieldMono<hpmc::ShapeSphere>"
```

Obviously, it can be fixed by loading hpmc first, and then jit. But this is not really a sustainable solution (and it would be a hack if applied inside jit.py). The real culprit is the unwanted dependency between CMake subdirectories. I don't think CMake supports linking between sibling subdirectories, at least not without extra effort. I believe there should not be a cross-depency in the first place, which means that the current design of using HPMC classes inside the jit plugin is flawed and needs to be revisited.

Any takers, @vyasr, @joaander  ?

**Comment by jglaser** [comment]
Plus, we need unit tests for the jit package

**Comment by mphoward** [comment]
Can this not be fixed by adding

from hoomd.hpmc import _hpmc

to jit/external.py? Base-derived dependencies exist all over the place (between md and hoomd, between mpcd and md, between external plugins and any hoomd component), and I think I’ve always been able to get them to work that way.

**Comment by jglaser** [comment]
> Can this not be fixed by adding
> 
> from hoomd.hpmc import _hpmc
> 
> to jit/external.py? Base-derived dependencies exist all over the place (between md and hoomd, between mpcd and md, between external plugins and any hoomd component), and I think I’ve always been able to get them to work that way.

Right, base-derived dependencies would be supported as a parent dependency between, say _hoomd and _jit, by linking the shared library to the dependency, because hoomd is in the top level directory. But this approach fails between adjacent subdirectories. That said, I wasn't aware that mpcd has the same issue, and that we consider solving these dependencies through python's dynamic linker (`import ..`) a valid solution. It *might* create confusion for plug-ins, but is perhaps acceptable.

**Comment by mphoward** [comment]
If I remember right, mpcd is properly linked against md, which can be done between siblings provided that the subdirectories are included in CMake in the correct order so that the needed targets have already been created. We’ve had no issues linking plugins against mpcd.

As I understood it, and maybe this is not right, the issue you identified is with pybind11 (and may just be part of its design). The base classes exist in a different extension module, which I thought meant that this module needs to be explicitly imported at the python level in order to create a derived type from those objects. Maybe that is not correct? It’s the workaround I’ve used since 2.0 was released.

**Comment by mphoward** [comment]
Btw, I think the INSTALL_RPATH is not set correctly either in CMake, which may also be part of the problem. You need to add the relative path to hpmc (see the mpcd file as an example).

**Comment by mphoward** [comment]
One other thing: it doesn’t look like _jit is linked against _hpmc at all in CMake. This is probably not strictly necessary to build _jit because the base class is likely header-only. But, the base object would still need to be imported in python. Just my two cents, someone with better knowledge of the design of those components can probably figure out how to resolve these issues correctly. :-)

**Comment by vyasr** [comment]
When making these changes I recall looking at mpcd specifically as an example of how this could be done, but I think when Josh and I went over it we weren't quite sure what was necessary to get the cross-package dependencies working so I just chose whatever solution made things worked. The fundamental reason this problem arose, though, is the fact that we wanted the JIT external field to be able to hook into the existing HPMC external field support. I had originally added completely independent logic to account for the JIT field (similar to how the patch energy is currently just evaluated separately and added to the external fields), but we ended up deciding to merge the functionalities for external fields.

I'm not sure which solution makes the most sense; however, I will say that introducing an additional logic path for the evaluation of the JIT field just to avoid the cross-package dependency leads to more verbose and more confusing code, which is why we made the switch in the first place. So I think it's to our benefit to try and resolve this in a way that doesn't remove that dependency entirely.

**Comment by joaander** [comment]
> Plus, we need unit tests for the jit package

@jglaser  We have the following tests:
* https://github.com/glotzerlab/hoomd-blue/blob/maint/hoomd/hpmc/test-py/test_jit_external_field.py
* https://github.com/glotzerlab/hoomd-blue/blob/maint/hoomd/hpmc/test-py/enthalpic_interaction.py

Feel free to add additional tests.

**Comment by joaander** [comment]
> Linking `_jit` to `_hpmc` does not solve the problem. `jit/__init__.py` must import `_hpmc` as @mphoward implemented for `mpcd`.

`pybind11` docs: https://pybind11.readthedocs.io/en/stable/advanced/misc.html#partitioning-code-over-multiple-extension-modules
We are essentially doing the same thing, but in python instead of C++.

**Comment by jglaser** [comment]
Confirmed working now, with pull request #359 merged.
