### ISSUE TITLE
Property API

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#398]
## Description

Parameters to HOOMD script command objects should be accessible by property.

## Proposed solution

Properties are more pythonic than setters. They also provide a more natural way for users to read current values. Examples:
```
lj.mode = 'shift'
integrator.dt = 0.001
nvt.kT = 0.5
nvt.tau = 1.0
mc.d = 0.2
```

## Additional context

Some properties in HOOMD are double buffered: stored in both python and C++. The python value is authoritative and copied to C++ at the start of a run. We should clearly document which properties are buffered. When refactoring, we should remove buffering and access the C++ values directly where possible.

## Questions

How should we map potential parameters to properties? They currently allow multiple named values to be set in a single call:
```
lj.pair_coeff.set('A', 'B', epsilon=2.0, sigma=1.0, alpha=0.5, r_cut=3.0, r_on=2.0);
```
They also allow the same parameters to be set for multiple type pairs:
```
lj.pair_coeff.set(['A', 'B'], ['C', 'D'], epsilon=1.5, sigma=2.0)
```

**Comment by mphoward** [comment]
I am working on another project that needs to handle pair parameters, and I settled on making an object that thinly wraps a dict of dicts. The first dict is keyed on all the `(i,j)` pairs for types in the system, while the other dicts are keyed on some preset list of parameters (although it is not necessary to initialize either of them first, you could do this lazily and defer until later).

I use `__setitem__` to process the key, and then loop through all of the parameters passed in as a dict:
```
coeff['A','A'] = {'epsilon': 1.0, 'sigma': 1.0}
```
This makes it safe to call `__setitem__` multiple times on the same pair.

To support setting multiple types simultaneously, you could detect if either `i` or `j` in the key passed to `__setitem__` is iterable.

To access the values, you could use `__getitem__`. To be safe for this call, the `(i,j)` pairs need to be stored upper triangular internally so that someone doesn't do `coeff['A','B']['epsilon'] = 2.0`, which would fail to set `coeff['B','A']['epsilon']` if `(i,j)` and `(j,i)` were stored separately.

So, the API would look something like:
```
lj.coeff['A','A'] = {'epsilon': 1.0, 'sigma': 1.0, 'rcut': 3.0}
lj.coeff[('A',B'),'B'] = {'epsilon': 2.0, 'sigma': 1.0, 'rcut': 2.**(1./6.)}
```

**Comment by jglaser** [comment]
We need to include the `hpmc` APIs (like, `set_fugacity()`. See #403

**Comment by b-butler** [comment]
Currently we have looked at using two different paths for operations currently: one for parameters that are not type dependent and another for those that are. The `_Operations` base class implements `__getattr__` and `__setattr__` to handle both parameters types through object internal `dict`s for each one. For typed parameters the syntax on the API branch is currently `operation.type_var['type']` for getting and setting. Like @mphoward's similar problem the internal value can be a dictionary, but it could also be any other type. In the case of HPMC integrators, the `d` parameter has a number for each type key. This current implementation supports required arguments, defaults, and iterative indexing.

**Comment by joaander** [comment]
Implemented in `feature/new-object-API`.
