### ISSUE TITLE
Use externally provided header libraries

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#420]
## Description

HOOMD should pull established packages, such as Eigen, cereal, pybind11, and posibbly CUB from the external sources rather than maintaining them as git modules.

## Proposed solution

Eigen, cereal, and pybind11 are all widely available packages (macports, homebrew, conda-forge, arch, ubuntu, etc...) and provide cmake config scripts. To use them, we simply need:

```
find_package(Eigen REQUIRED NO_MODULE)
find_package(cereal REQUIRED NO_MODULE)
find_package(pybind11 REQUIRED NO_MODULE)

target_link_libraries(_hoomd PUBLIC cereal Eigen3::Eigen)
```
And to replace all of the ` #include <hoomd/extern/${package}/include/${package}/file`
with `#include <${package}/file>`

For CUB, we will need to write a minimal `FindCUB.cmake` script. CUB is unfortunately not widely available. However, this is necessary as we may need the flexibility in the near future to include different CUB libraries at configure time. Perhaps we can think of an alternate solution to this issue, as CUB is only included in 9 places across all of HOOMD.

## Additional context

For developers, I think maintaining the minimal CMake code will be less work in the long run than maintaining the submodules for these established packages. Submodule merge conflicts are hard to solve and maintaining the forks takes effort as well.

For users who build HOOMD from source on HPC systems, installing ~4 additional packages before compiling HOOMD would be an energy barrier. These are all header only libraries that are trivial to install, so we can mitigate this barrier by providing a helpful script that installs them. The full build process into a virtual environment might look like:
```
$ python3 -m venv /path/to/env
$ source /path/to/env/activate
$ cd /path/to/hoomd
$ python3 install_required_headers.py
$ mkdir build && cd build
$ CMAKE_PATH_PREFIX=/path/to/env cmake ../
$ make install -j4
```
The script could take arguments listing which headers to install in case a user wishes to use some headers from the system and others provided by the script:
``` $ python3 install_required_headers.py CUB ```

Not well established packages, including libgetar, random123, upp11, nano-signal-slot, and quickhull would be left as git modules. These do not update often and only intersect a small cross-section of HOOMD, so further maintenance of these modules is less effort than creating and maintaining packages or always needing to use the header install script.

**Comment by mphoward** [comment]
This is a good idea in case we ever add external compiled libraries that can be optimized for a given system.

Regarding CUB, based on my recent experience, it may no longer be necessary to use this library in several places in hoomd. Since CUDA 9, thrust is, for the most part, already calling CUB under the hood to do sorts and reductions. And, since Jens has undertaken the effort to be able to pass an allocator to thrust, there is not really a performance hit from thrust needing to create its own temporary storage.

The one place where CUB is still valuable is for `WarpTools.cuh`, where it is used to ensure a consistent warp operation interface. However, this might be simplified by only copying in a handful of CUB headers that are needed, rather than requiring the full library.
