### ISSUE TITLE
Error out if pair coefficient keyword is invalid

### ISSUE THREAD

**Issue by mphoward** [glotzerlab/hoomd-blue#428]
## Description

Currently, `pair_coeff.set` will accept any keyword-value pairs that are thrown at it and stashes them in a dict. Then, the coefficients that are actually needed are processed from the dict by the potential. This does not catch invalid keywords, which causes problems if the user meant to override a default coefficient (e.g., intending to override `r_cut` but actually setting `rcut`). Such errors are silent.

## Proposed solution

The pair coefficient dictionary should throw an exception if the keyword is not in the list of valid options.

## Additional context

This should probably be resolved alongside #398 .

## Developer

I'm unable to work on this at this time, but documenting for future.

**Comment by b-butler** [comment]
In the v.3.0 API branch, error checking is deferred until operations (integrators, analyzers, updaters, etc.) are attached to C++ objects. Error checking is then done, and errors will be raised if all types are not specified. When in the attached state, all indexing must be type correct. This cannot be enforced beforehand because we are deferring initialization until the user requests to have operations 'scheduled' or the `Simulation` object's `run` method is called.

**Comment by mphoward** [comment]
This is an OK solution so long as (1) there are no default coefficient values anywhere in HOOMD or (2) invalid parameter keywords are still rejected. The main purpose of this issue is to avoid silent typos like rcut vs r_cut, which are tricky to find and debug in a script. You should be able to reject invalid keywords using python without needing the C++ object using, e.g., a white list, right?

**Comment by joaander** [comment]
Yes, the new `TypeParameterDict` class only allows users to set expected keys. Unexpected keys like `rcut` result in an error.

https://github.com/glotzerlab/hoomd-blue/blob/16de7f4ccd4e32ae5e1092fa89143b84b1549443/hoomd/parameterdicts.py#L124-L142

What we have to defer is validating that parameters for all types (or type pairs) are set because the number of types is not known until the system is initialized. We chose to defer this until the operations are scheduled (their C++ classes are instantiated and added to `System`).

Example:
```
a = hoomd.hpmc.integrate.Sphere(seed=1)
a.shape['A'] = dict(d=5)
--> Error: Keys must be a subset of available key
a.shape['A'] = dict(diameter=1.0)
s = Simulation()
s.operations.add(a)  # available types still not known
s.create_from_gsd('init.gsd') # load file with types 'A', and 'B'
s.schedule()
--> Error: diameter has no default for type 'B'
s.shape['B'] = dict(diameter = 2.0)
s.schedule()
--> Success
```

We did discuss the possibility of providing default values for everything. This would allow a simulation to schedule and run even if the user set no type parameters. I am concerned that this would lead to unexpected behavior. I would welcome further discussion on this.

**Comment by mphoward** [comment]
Great! I like this way of handling things. I also prefer not to have default values, as I think this can lead to unexpected behavior or errors, as you say. I would rather have the user state their intent for all parameters, even if it is slightly more verbose.

**Comment by b-butler** [comment]
@mphoward I would note that many parameters still have defaults, just not all of them. Also, the user can change the default if wished to have all the same values for all queried types.

**Comment by joaander** [comment]
Implemented in `feature/new-object-API`
