### ISSUE TITLE
take_snapshot missing positional argument

### ISSUE THREAD

**Issue by drozzy** [glotzerlab/hoomd-blue#453]
## Description

When I try to call this function (as docs outline in "Relevant methods:" on [hoomd.data](https://hoomd-blue.readthedocs.io/en/stable/module-hoomd-data.html#hoomd.data.system_data.take_snapshot) page):
```
hoomd.data.system_data.take_snapshot()
```

I get the error:
```
TypeError: take_snapshot() missing 1 required positional argument: 'self'
```

The snapshot I'm trying to get is for the Lennard Jones tutorial:
https://nbviewer.jupyter.org/github/joaander/hoomd-examples/blob/master/Tutorial%20-%20MD%20-%20Lennard%20Jones.ipynb

(I want to be able to capture the state of the system, for machine learning purposes)

**Comment by mphoward** [comment]
As in the documentation examples, this is a member method of a system:
```
snapshot = system.take_snapshot()
```
where `system` is the object returned by a `hoomd.init` command. You are getting an error because you are calling the function explicitly, and so you are missing the `self` argument implicitly passed by python to an object's member methods.

In future, I recommend directing questions like this to the hoomd-users mailing list, where you will be able to receive help from the full community:

https://groups.google.com/forum/#!forum/hoomd-users

**Comment by drozzy** [comment]
It's just the "system" variable is never defined in the tutorial, so it is hard to know where it comes from.

I think it "is" a bug in the documentation.

Thanks. Will use google group from now on.

**Comment by mphoward** [comment]
Examples of saving the `system` variable returned by an `init` command are documented in multiple places on the page you referenced, but this comes before the command that you looked at. See, for example, the `restore_snapshot` documentation immediately above the `take_snapshot` documentation.

**Comment by drozzy** [comment]
It is not clear that the `init` here is the same as `hoomd.init` in the tutorial. But maybe that's just me.

**Comment by mphoward** [comment]
You are welcome to submit a PR proposing revisions to this documentation if you feel that it is not sufficiently clear, reopening this issue with a "documentation" tag.

**Comment by joaander** [comment]
The new documentation for `Simulation` and `State` clearly explain how to get snapshot objects.
