### ISSUE TITLE
Easier GPU support?

### ISSUE THREAD

**Issue by drozzy** [glotzerlab/hoomd-blue#516]
Is it possible to somehow have a GPU-supported version that is installed via pip or conda?

It is not clear how to run this with GPU (as I'm not familiar with compiling/building process).

When I try to initialize it with GPU I get:
```
GPU execution requested, but this hoomd was built without CUDA support
```

Thank you.

**Comment by joaander** [comment]
This was not possible previously on conda-forge due to licensing https://github.com/conda-forge/conda-forge.github.io/issues/63. Now it seems that they may be starting to support CUDA builds: https://github.com/conda-forge/conda-forge.github.io/issues/901

I do not plan to implement this myself. I welcome pull requests on https://github.com/conda-forge/hoomd-feedstock/
I have no plans to provide a pip installable package of HOOMD.
