### ISSUE TITLE
Add testing for ParticleFilters

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/hoomd-blue#534]
## Description
Add testing to `ParticleFilters`.

## Proposed solution
Add tests for existing particle filters in `hoomd/filters.py`

**Comment by joaander** [comment]
In addition to testing, we should implement the particle filter updater and document that the particle filters are applied 1) when particles are added or removed from the system and 2) when the particle filter updater is triggered. 

In the MD implementation, we will need to consider how to handle integration methods and compute thermos when their groups update membership. Currently the integration methods provide a count of the number of degrees of freedom they provide to the system so that Thermo can compute the correct temperature.

**Comment by joaander** [comment]
Fixed in #634
