### ISSUE TITLE
No error issued when different particle vertices for specified for different ranks

### ISSUE THREAD

**Issue by Tobias-Dwyer** [glotzerlab/hoomd-blue#569]
## Description

When different vertices are applied to each rank in a hoomd run, no error is produced meaning that different particles can be run for each rank. This has been shown to be a problem if the user is generating a new particle configuration each time the code is run meaning that for each rank the particle vertices will be different. 

The issues become clear during compression of a simulation because the system is unable to properly run overlap checks. 

to reproduce the problem, initialize the signac workspace and run the signac project file submit_job

## Script

```python
# Include a minimal script that reproduces the problem
you can reproduce this problem on great lakes with the script provided here. 
The reduce overlap code is what generates a slightly different particle for each rank based on the isovalue file which is just the file for the vertices of the particle. 
[Problem_Reproduction.zip](https://github.com/glotzerlab/hoomd-blue/files/3990248/Problem_Reproduction.zip)



```

## Configuration

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
- Conda package
- Compiled from source
- glotzerlab-software container

Versions:
- Python version: 3.7
- **HOOMD-blue** version: 2.8.1

**Comment by joaander** [comment]
@b-butler This issue is general to all param and TypeParam dict values. The user can break things by specifying different values (e.g. temperatures) on different ranks. In v2.x I have strategically inserted broadcast calls on parameters where I expect users to pass different values (such as seed which many users set to a clock value). The broadcast call passes the value from rank 0 out to all the ranks and any values set on other ranks are ignored.

For v3 we could consider a general solution for all parameters and type parameters. This would require writing and exposing broadcast methods for all possible types that users may pass to params and TypeParams. Given that these may be user-defined classes (e.g. particle filters) or nested dicts, we may need to rely on pickle to pack and unpack the objects. Alternately, we could just not broadcast custom types and assume that users pass them in correctly.

**Comment by joaander** [comment]
I'm not sure a general solution is possible given the nature of the data model. We will need to address topics like this in a future MPI tutorial.
