### ISSUE TITLE
Correct module-hoomd-analyze document

### ISSUE THREAD

**Issue by jekw90** [glotzerlab/hoomd-blue#590]
## Description
hoomd.analyze.log module allows user to log energies related to integrator. 

In the hoomd-blue documentation (https://hoomd-blue.readthedocs.io/en/stable/module-hoomd-analyze.html), for the md.integrate.nvt integrator, it is stated that there are two reservoir energy quantities,

nvt_reservoir_energy_groupname

and

nvt_mtk_reservoir_energy_groupname

Here, nvt_reservoir_energy_groupname does not dump the energy (it dumps 0), while the nvt_mtk_reservoir_energy_groupname seems to dump energy correctly.

So, documentation may be corrected such that nvt_reservoir_energy_groupname would be removed.

Thank you very much!!

## Script

```python
# Include a minimal script that reproduces the problem

```

## Configuration

Platform:
- Mac
- Linux
- GPU
- CPU

Installation method:
- Conda package
- Compiled from source
- glotzerlab-software container

Versions:
- Python version: ?.?.?
- **HOOMD-blue** version: ?.?.?

**Comment by joaander** [comment]
Thanks for reporting the discrepancy. There are a lot of documentation issues with the loggable quantities in general. The entire logging mechanism has already been completely rewritten for v3 and the loggable quantities are documented as class properties.

Closing, since this is already solved in v3.
