### ISSUE TITLE
V3 Randomize Velocities API

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/hoomd-blue#648]
## Description

There may be a better, more general way to expose the `randomize_velocities()` API that is currently done through the integration methods

## Proposed solution

We had talked about potentially exposing this API through the simulation state instead of through the integration method. For example, it might be used via `simulation.state.thermalize_velocities()`, instead of `nvt.randomize_velocities()` for an `NVT` integration method.

## Additional context

Another option we had considered is moving the implementation of `randomize_velocities()` to the `_Method` class if we decide not to move it to the state.

## Developer

Once we come to a decision as a group as to how to proceed, then yes, I could handle this if need be.

**Comment by vyasr** [comment]
To give some context, I proposed moving `randomize_velocities` into the state for a couple of reasons. The reason this discussion came up is because the v3 API introduces additional complexity associated with the attachment process, which allows simulations to be specified almost completely without ever creating C++ objects. While this process is desirable in general because it allows composability of protocols in very natural ways by just importing different python modules that each set up e.g. a force field via a set of pair potentials, it introduces difficulties for any method that is meant to occur instantaneously rather than at some specific interval. One common example is resizing a box, and randomizing velocities is another. Since conceptually methods are meant to be `Triggered` in the v3 setup, having one execute instantaneously is an antipattern and also causes implementation problems because it then requires that the simulation state be attached to the C++ instance. Since randomization is really a property of the state, not a property of the integrator, it makes sense to move the logic there, and it conveniently resolves the difficulties mentioned above. The one downside is that initializing velocities in a way consistent with integrator parameters (i.e. with the same temperature applied to the same groups of particles) is now the user's responsibility.

**Comment by jglaser** [comment]
An issue is also that internal integrator variables (like the thermostat or barostat degrees of freedom) are currently being randomized because they, too, are velocities, which is one if the reasons why the randomization is specific to the integration method being used. Differently from particle velocities, there is only a finite number of them (such as, one for every box degree of freedom). We would need to find a way how to extend the state by these variables, depending on which integration method is used.

**Comment by joaander** [comment]
I think the class-specific (NPT, NVT, etc..) degrees of freedom should be accessible as properties of that class. We can provide a class-specific thermalize method for those that have it along with the generic method in `State` for particle velocities. This means that thermalize both types of velocity takes 2 lines of code, but it is explicit about what is being set and where. Both thermalize calls should be immediate operations, which means if we want to allow it to be called before attaching we will need to move the implementation to Python.
