### ISSUE TITLE
Randomly choose moves from eligible set

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#657]
## Description

There needs to be a way to randomly select and run a single `Updater` from a set of eligible ones to execute in a given time step (e.g. `IntegratorHPMCMono<Shape>`, or `UpdaterBoxMC`, `UpdaterMuVT` or `UpdaterClusters`). I cannot see how it is correct to run them in series without permuting their order. I suspect we're violating detailed balance.

**Proposed solution**: in v3, it may be possible to implement something like a `RandomTrigger` to which individual classes can subscribe, and which notifies the class that is actually selected to run during the time step. It may even be easier to implement the entire `run()` loop in python instead of in `System.cc`.

Additionally, the grid shift would become an `Updater` and `nselect` a probability instead of a fixed period. The MC integrator should no longer be special, instead it should just be a possible member of the move set.

## Script

I suspect that some of my preliminary simulation results, which involve a combination of cluster moves and local moves, are affected by this. These involve the `depletants_new` branch for which I will soon open a PR.

## Output

N/A

## Expected output

N/A

## Configuration

Versions:
- **HOOMD-blue** version: 2.x

## Developer

Yes, if the devs for v3 would also agree to take this up

**Comment by b-butler** [comment]
@jglaser, I think the idea of a `RandomTrigger` makes sense. The main problem that I see is that currently we treat the `HPMCIntegrator`s the same as an MD integrator (i.e. special). I don't know if it makes sense to make the MD integrator behave the same as you are proposing for MC.

What would you think about having a `MCIntegrator` object that then pooled trial moves from a group of contained *methods* like the MD integrator? Then the box, displacement, cluster, and insertion/removal moves would all be *methods*. They could have a probability associated with them, and should address the concern you pose.

**Comment by jglaser** [comment]
There is some (legacy) justification for treating `IntegratorHPMCMono` in a special way, because it stores the shapes, computes the MC interaction range and other C++ classes reference it, rather than the other way around. Unless we're factoring out those bits, it would make sense to leave the special status of local move integrator as is, however providing that it's `update()` method is only called with a given probability, as proposed in the change set referenced above.

However, I do like the `MCIntegrator` idea. Ideally, it would

1. maintain the shape parameters
2. store a list of trial moves, which it executes randomly

It could be a pure python class (or a very lean C++ class with only the shape data structures implemented, but keeping all the logic in python otherwise).

I am not at all proposing to have the MD integrators behave the same way. The timestepping / fixed update order makes perfect sense in MD, because it was designed for MD. Any changes we make to HPMC classes should be pending the upcoming `depletants_new` PR (very soon).

**Comment by b-butler** [comment]
Hmm, you know the C++ code base better than me, would it be possible to have the shape move be included in the `MCIntegrator` updater, I proposed. My concern is that we would be treating a specific trial move differently than the others which could be confusing to users. We could require that a `MCIntegrator` always contains at least a `IntegratorHPMCMono` object. Making the update method only actually update randomly, while it should work since then any ordering of trial moves is technically possible, but seems more like we are hacking a solution (if necessary that is fine, being right is more important).

In the end, that may be more of a refactoring than is warranted given the size and complexity of the classes involved. It may be best though to have a conversation with us two and @joaander (or anyone else who wants to join) and think of how best to approach this.

**Comment by jglaser** [comment]
I think I may not have made myself clear enough. I am proposing to separate the shape **data structures** from the local move **update**. All HPMC functionality operates on shapes, so these data structures should be shared among the different type of moves. E.g., there would be a `MCIntegrator` as discussed above, and, say, `HPMCLocalUpdate`, `HPMCClusterUpdate`, and `HPMCBoxUpdate` . While this represents a refactor, I think it would help to express the concepts involved in Markov Chain Monte Carlo in a better way. I am happy to discuss this proposal with you and @joaander and whoever else is interested, and can help implementing it.

**Comment by b-butler** [comment]
Ah, separating the data from the objects that act on it, that could work.

**Comment by joaander** [comment]
There shouldn't be a problem running the various updaters sequentially in the same order. [Manousiouthakis and Deem](https://doi.org/10.1063/1.477973) show that sequential moves that obey local detailed balance result in a Markov chain that obeys the more general global balance condition.

That being said, I would support a refactor of the shape data outside the MC integrator, but I would really like to first finalize and merge the many other major refactoring efforts we currently have in progress. Would you also refactor the global check_overlap test outside the integrator to this data representation class?

**Comment by jglaser** [comment]
That paper is very nice, and I wasn't aware of it. The combination of the cluster moves local moves should fulfill the criteria for Markov chain convergence, even though the cluster moves in #659 are no longer ergodic (they sample only eight different orientations per particle). However, as their combination with local moves is ergodic, and moreover, the cluster flip probability is finite, this should make the transition matrix regular, guaranteeing convergence together with the fact that it leaves the canonical distribution invariant. This is more like a hunch than a formal proof, and it looks like we really need some good validation tests for the equation of state of anisotropic particles.

**Comment by scmartin** [comment]
I was hoping to simulate confined fluids in confinement, but realized that the muVT updater doesn't support walls. Our group is debating whether to develop this functionality in HOOMD and make a pull request or write our own stand-alone code, but I think this issue is particularly relevant for our decision; depending on how drastic the refactorization is, this could be in the works for quite awhile, I'm guessing. Do you have a firm plan for how this will be implemented in 3.0?

**Comment by joaander** [comment]
@scmartin I would recommend adding the functionality to HOOMD-blue. There should be no need to re-implement all of the other machinery of an MC engine because HOOMD is lacking this one feature. I think adding wall support to MuVT is a straightforward addition of a check of the insertion particle against the walls in the insertion step. @jglaser might have more to add - he wrote the MuVT code.

We have not yet begun refactoring the walls for v3.0, so now is the perfect time to make that change. You can add the functionality based on the `next` branch. Then, when we get to the wall API refactor we can refactor the MuVT code along with the rest of HPMC. My apologies, the HPMC wall code is some of the less professional code in HOOMD - if you have any questions about what methods you need to call, feel free to ask in #665 or contact me and we could discuss in real time.

@jglaser does have a major refactor of HPMC on #659, but the modifications to MuVT are minimal and should not conflict.

Are you asking specifically about the random move choice mentioned in this thread? We currently have no plans to implement this. However, with the new `Trigger` API in the 3.0 API (on `feature/new-object-API`) there is a straightforward way to run Updaters with a random probability on any given step. Refactoring to run the Integrator less often than every step would take more work but is something we could discuss if it enables an essential use-case. For now, most use-cases seem to be handled well by setting `nselect=1` to prove a mix of 1 trial move per particle with 1 box or 1 insertion move. One could also perform more than 1 insertion move with an update to muVT to support a configurable number of insertion moves.

**Comment by jglaser** [comment]
Indeed, since the Updater already respects patch potentials, making it support external potentials such as walls is probably a five line change, if not less. @scmartin let me know if you need directions.

**Comment by scmartin** [comment]
@joaander I was indeed asking about the random move choice in this thread. From what we have observed, moving from nselect=10 to nselect=1 for the integrator gives significantly faster decorrelation of the density with only minimal slowdown. We think that we could probably push this further and get even better sampling efficiency (though clearly at a ; perhaps your suggestion of updating the muVT to have a configurable number of attempts would help address this issue.

Also, I haven't had a chance to read through the Manousiouthakis and Deem paper you referenced above, but it sounds like you are fairly confident that using sequential moves still sample from the correct distribution. 

@jglaser Is there a particular branch I should base this work off of?

**Comment by scmartin** [comment]
So looking at the code for this, it saw that in the integrator the ExternalField.energydiff() method is used to change the \DeltaU, but I'm not sure how to apply this for the case of insertions (deletions), where there is no old (new) position at which energydiff() to calculate the energy.
