### ISSUE TITLE
Grand Canonical Walls

### ISSUE THREAD

**Issue by kmuir1235** [glotzerlab/hoomd-blue#665]
## Description

 When implementing a sphere wall into a grand canonical script, the wall is not accounting for the insertion and deletion moves.
## Script

```python
ext_wall = hpmc.field.wall(mc)
ext_wall.add_sphere_wall(radius = 25.0, origin = [0, 0, 0], inside = True)

```

## Output

 The particles on the outside of the wall were not doing translational moves but were still being inserted and deleted.

## Expected output

Along with not moving, particles on the outside of the wall should not be inserted or deleted.

**Comment by joaander** [comment]
Thanks for the feature request.

**Comment by scmartin** [comment]
@joaander Moving the conversation from [657](https://github.com/glotzerlab/hoomd-blue/issues/657#issuecomment-650272947), since this feature request is where it belongs. I think it makes sense to for the ExternalField classes to include a function that simply computes the energy for a single particle. This could be used in the energydiff() command and for insertion/deletion commands. This might have other uses as well.
The other option would be overloading energydiff() to have the option to take a single particle and just make sure to apply the correct sign to the change in energy when inserting or deleting.

**Comment by joaander** [comment]
Yes, the other external fields all have functions that compute the energy of a given particle configuration with a wall - they just don't expose this. In these cases, `energydiff` computes the two single configuration energies and returns the difference. In the wall field, the previous configuration is ignored and `energydiff` is equivalent to evaluating whether the given new position/orientation overlap with a wall.

Feel free to add a new API to the base class for evaluating a single given particle configuration or just use `energydiff` as is for walls now. I plan to refactor this whole API from the ground up when we update it to v3.

**Comment by scmartin** [comment]
So to access `energydiff` I tried using the integrator's `getExternalField()` member, but it returns the base `ExternalField` class instead of `ExternalFieldMono` where `energydiff` is declared. Does this require changing `getExternalField `to return the derived class so that the `energydiff `member is accessible, or is there another approach I'm missing?

**Comment by joaander** [comment]
My apologies, this API was not well thought out. The main issue here is that energydiff requires the shape information so that it can evaluate the shape against the wall. This means that any class that calls it needs to be templated on `Shape` so that it construct and test particles with shape against that. This is why `energydiff` is not available in the base class.

UpdaterMuvt is templated on Shape, so this isn't a problem. Add a new `get_external_mono` method to IntegratorHPMC that returns `m_external` which is of the correct type to call `energydiff`.

**Comment by scmartin** [comment]
I have implemented this and it seems to be working. I'm further testing it. Thank you for the guidance.

**Comment by joaander** [comment]
Great! Do you plan to submit a pull request after you complete your testing?

**Comment by scmartin** [comment]
I would certainly be willing to. I've not actually created a pull request before, so it may take me a couple of days to get to it and to figure it out.

**Comment by joaander** [comment]
Let us know if you have any questions about the process.
