### ISSUE TITLE
Reduce output to stdout/stderr

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#684]
- Device doesn't print output on construction
- Welcome message method for users to opt-in

**Comment by vyasr** [comment]
Since there are many cases of output printing in HOOMD, this will be an issue corresponding to many PRs. I've created a feature branch `feature/reduce_output` (from `feature/new-object-API`) that I'll use as a target for each of these PRs. I'll keep a checklist here of the things that need to change and the corresponding PRs.

[ ] - cite.py output: #740 
[ ] - ExecutionConfiguration output:

**Comment by joaander** [comment]
We can merge these directly into `feature/new-object-API` one at a time.

**Comment by joaander** [comment]
FYI: I'm going to tackle the ExecutionConfiguration as part of a larger refactoring on #747 .

**Comment by joaander** [comment]
We also need to remove the 10-second output line from `System::run` and the `printStats` methods from classes that implemented. Where appropriate, replace `printStats` with loggable properties that provide the information in a more granular fashion (e.g. number of dangerous builds in the nlist).
