### ISSUE TITLE
Decide how properties in build_info should be exposed

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/hoomd-blue#744]
Removed during the work on #735 
Issue created at @b-butler 's request.

**Comment by j-proc** [comment]
## Description

The metadata, such as SHA string of the HOOMD build was previously in context.py. The global bib and options objects were also housed within context. These have been moved to the top namespace of HOOMD and the metadata exists in a build_info object.

How these are exposed and stored is up for discussion here.

## Proposed solution

Leaving these objects in the top namespace is not a significant issue.

## Additional context

context.py was removed because very little was left after context.initialize was removed.

**Comment by joaander** [comment]
Most packages put these in `__name__` type variable directly in the top level namespace - e.g. `numpy.__git_revision__`. and not in a class that must be instantiated to access. I would expect that these would be accessible in HOOMD as `hoomd.__git_sha1__`, `hoomd.__cuda_version__`, etc... 

Do you want to handle this on #735 or defer to a later PR?

**Comment by j-proc** [comment]
That's not an issue. I can handle this now and then it should be ready to close.

**Comment by j-proc** [comment]
The only point of possible is that I replaced the hardcoded version with one that references the c++. My thought was that it made sense to always have them match. However, if there's any code that tries to extract the version outside of a running python environment, this change would cause issues.

I left all the attributes as simple attributes rather than properties so that they can be changed by the user should they need to be for any testing.

**Comment by joaander** [comment]
Thanks! Attributes are fine, this is how most Python codes expose these. Please leave the hard-coded `__version__` - this is managed by `bump2version`.

**Comment by j-proc** [comment]
Done
