### ISSUE TITLE
Add duecredit support

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#748]
## Description

The cite module writes output to stdout when modules are imported or used.

## Proposed solution

We should either:
a) Remove the cite module and rely on users following the documentation on the web.
b) Refactor the cite module to work in a different way.

Seeking proposals from users preferring option (b).

**Comment by mphoward** [comment]
I originally added the cite module because I found it hard to find the references for features in the docs, and it was easy to miss stuff. I copied the behavior of other packages that force this information on the user at runtime. I find this convenient as someone who wants to see logged output from simulations, but I'd be OK removing this module if there is an easy & obvious way to find this information.

For option (a), can we add the information at [citing](http://glotzerlab.engin.umich.edu/hoomd-blue/citing.html) to the sphinx docs, under a TOC entry "How to cite HOOMD-blue" (or something like that). I think a lot of users only check the RTD pages since those stay up to date. (I check the other webpage for information maybe only once a year or less.) Putting this info here will also mean we can make PRs to update or modify as the code evolves. I think it would be good to do this even if some version of (b) is also done.

For option (b), the citations could probably be tweaked to only trigger when classes are constructed, maybe using a class that lives in the module namespace. You could declare all the citations at the top of the module (or even maintain just one central bibliography), and then decorate the classes that need certain entries. These would need to have a flag tracking whether the citation had already been printed if (when) you use multiple classes from the same module, and all classes would probably require the decorator.

There is also [duecredit](https://github.com/duecredit/duecredit) as an external option. I haven't used it before though.

**Comment by joaander** [comment]
Including the citation list in the docs is a good idea. We will certainly do that.

In v3, we plan to have no output to stdout under normal usage circumstances. Users need to opt in to the output. So the consideration for (b) I meant to ask about is how would users prefer to request/access that output? Should the output still go to stdout or be available as a string? Or should only the .bib file output be available?

**Comment by mphoward** [comment]
Gotcha, I would prefer having the citations print to the opt-in stdout with similar level of priority to what they have now (if by default all the output will be suppressed), ideally as features are used. Otherwise, it's easy for new users to miss that they should have written the bib file in the first place; more experienced users will likely know what citations they need without using any of this stuff. I don't see many use cases where I would want the citation as a string (what would somebody do with this? maybe print it to their own file?).

**Comment by joaander** [comment]
OK, so if we keep the module what would the API to print the citations be? Perhaps something like:
```
sim.bibliography.print_citations()
```
Different simulations can have different operations, so this would need to be tied to the simulation class and not a global module level variable. Operations would need to add their citation when added to the simulation. Users would need to call `print_citations()` after adding all of the relevant operations.

**Comment by mphoward** [comment]
I think something like that would work nicely.

**Comment by joaander** [comment]
@b-butler Any thoughts?

**Comment by b-butler** [comment]
I would just have a `sim.print_citations` function and have it go through all the operations each time it is called to generate the proper citation list. I don't see a need to keep the bibliography up to date unless we want to provide a programmatic interface for citations. We could also provide a `sim.citations` property string that would allow users to easily export citations to a `.bib` file.

**Comment by b-butler** [comment]
We just need a way for operations to denote their relevant citation which should be doable fairly easily in the current class structure.

**Comment by joaander** [comment]
@vyasr You investigated duecredit at one point. What is your take on this conversation? Should HOOMD continue to provide a citations list (available on request by the user) or should we avoid triplication and only offer citations on the web page and the readthedocs pages?

**Comment by vyasr** [comment]
I think that the two options we should consider are either 1) remove citation functionality entirely, or 2) use `duecredit` and remove `hoomd.cite`. `duecredit` allows you to either decorate specific functions/methods/classes or cite an entire module, it keeps an internal list to avoid duplication, and it supports both printing to stdout and writing to a file, so I don't see any benefit to rolling our own. The primary concern @joaander raised was that building up the bib file required running the script. That is a good point (`hoomd.cite` module has basically the same limitation), but I think we could overcome this by implementing the dry-run feature @mphoward suggested (documented in #506), which would be suitable for a quick run to dump citations if implemented.

Regarding whether it's worth maintaining the in-code citation functionality at all, I think the two sides of it are: 1) Users find extra output annoying, or 2) Users find it helpful to see the citation since they may not think to cite it without being warned. If we're no longer printing by default, neither of these concerns are relevant. @mphoward's statement about the citation being easy to miss and maybe hard to find in the docs is IMO more an indication that we need to improve visibility in the documentation rather than a sign that we should print it here.  If we're aligning with the rest of the Python ecosystem on trusting users to go look up citations on their own (which I'm fine with, that's what I've done in other packages I maintain), then I think the main benefit of enabling this support is that if we use `duecredit` users could easily generate a bib file with citations for all packages in their script that support the package, not just HOOMD. I think that could be helpful if we adopt it more broadly for our own packages, so I have a minor preference for adding this support. I'd say implementing the dry run would be a strong improvement here since (like Michael mentioned) less experienced users are very likely to forget to generate the files the first time around.

**Comment by mphoward** [comment]
I think @vyasr raises some excellent points. Based on what he outlines, I would also favor including the citations with `duecredit` (so they can be extracted from the script essentially statically by implementing the dry-run feature), and then reworking the docs to also make these citations more visible there.
