### ISSUE TITLE
Rename CSV to Table

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#778]
@b-butler noted during a demonstration that the CSV writer defaults to "pretty" formatting with a maximum of 5 decimal places, "centering" output values by default, and space-delimiting. The output CSV files from these settings cannot be parsed by `pandas.read_csv` using pandas' default settings. I recommend changing these values to `pretty=False` and left-aligned values separated by commas. This output method should adhere to [RFC-4180](https://tools.ietf.org/html/rfc4180#section-2) as well as we can, and should not truncate output values solely for "prettiness."

"Pretty terminal output" (the purpose of the current defaults) is still valuable, but I think that would be appropriate to provide in a separate class where centering/limited precision is the default behavior.

https://github.com/glotzerlab/hoomd-blue/blob/a7134d3f12c6242478a859b3e8c285cd9277af6b/hoomd/output/csv_backend.py#L63-L65

See also:
- https://en.wikipedia.org/wiki/Comma-separated_values#RFC_4180_standard

**Comment by joaander** [comment]
We have no intention of providing RFC-4180 CSV output. Users will be encouraged to use binary file formats such as GSD or HDF5 for logging scalar and vector quantities. The primary goal of the CSV class (which should be renamed) is for human readable output to the terminal.

Users that desire a standards compliant text format output can implement a custom analyzer and write it themselves, possibly with the use of libraries such as pandas.

**Comment by joaander** [comment]
Notes from an offline discussion:

To clarify, it is my goal to provide a clear, functional, and high performance design. I am strongly encouraging the use of binary logging because a) it is faster to both read and write than text based logging b) binary formats can represent non-scalar objects cleanly in their natural form (e.g. net_force=(Fx, Fy, Fz), pressure_tensor=(Pxx, Pxy, Pxz, Pyy, Pyz, Pzz), and dictionaries dict(epsilon=1, sigma=1)) and c) binary formats enable new rich possibilities for analysis e.g. by logging the per-particle LJ force and energy, or the list of all overlapping pairs of particles. Many of the design decisions  in HOOMD v3 are built around these principles - e.g. providing `pressure_tensor` as a loggable instead of the 6 elements individually. 

The CSV writer will be renamed to `Table` to better reflect its purpose. `Table` is meant to replace the information that HOOMD v2 writes to `stdout` during a `run`, with a more flexible interface to allow for custom quantities to be monitored by a human using `tail`. The replacement to `analyze.log` is in `GSD` which is now capable of saving most loggable quantities (the exceptions are a few elements of the `state` dictionary). We also planned to provide a `HDF5` writer #652. So, I have no plans to implement RFC-4180 compliant output for machine readable purposes.

That being said, I understand that some users may still desire such output. They are welcome to submit a PR that enables it. As @bdice stated, strict adherence to the RFC-4180 spec is required, including:
* Use of the CRLF line break
* Space characters should only be included when part of the field
* Use of double quotes to escape characters in strings
* Ensure that the optional header line is written only once, or not at all
* Ensure that there is at least one record and one field
* Represent `None` values as empty fields
* Represent floating point values at full precision

I would suggest adding `rfc4180=True` option to the `Table` constructor as a convenience to enable this.

**Comment by bdice** [comment]
@joaander Thanks for writing that summary, I am happy with the design consensus we reached. This issue can be closed or renamed as desired, since my original suggestion is not relevant anymore.
