### ISSUE TITLE
Misleading exception handling for properties

### ISSUE THREAD

**Issue by jglaser** [glotzerlab/hoomd-blue#904]
## Description

When an exception is thrown inside a property getter of an operation, it is converted into one wrongly saying that that property was not an attribute of the class.

## Script

See unit test in PR #659 here

https://github.com/glotzerlab/hoomd-blue/blob/1e13e4b4c2123440593afb1b6dba61d11a022df3/hoomd/hpmc/pytest/test_clusters.py#L137-L157

## Output

```
self = <hoomd.hpmc.update.Clusters object at 0x20004a641198>
attr = 'avg_cluster_size'

    def __getattr__(self, attr):
        if attr in self._reserved_default_attrs.keys():
            value = self._reserved_default_attrs[attr]()
            object.__setattr__(self, attr, value)
            return value
        elif attr in self._param_dict.keys():
            return self._getattr_param(attr)
        elif attr in self._typeparam_dict.keys():
            return self._getattr_typeparam(attr)
        else:
            raise AttributeError("Object {} has no attribute {}".format(
>               type(self), attr))
E           AttributeError: Object <class 'hoomd.hpmc.update.Clusters'> has no attribute avg_cluster_size

hoomd/operation.py:101: AttributeError
```
## Expected output

An exception telling me where the error occurs inside the getter method (which was ultimately the case).

## Configuration

Versions:
- Python version: 3.7.0
- **HOOMD-blue** version: `depletants_new` branch

**Comment by joaander** [comment]
This is a design "feature" of the Python language which uses exceptions for ordinary things like testing if attributes exist. @b-butler and I have run into this several times and have not been able to think of a good solution for this.

**Comment by joaander** [comment]
`@property` (and `@log` which also makes a property) turn getter/setter methods into properties accessed by `object.property_name`.  Python determines if the property exists by calling the getter and testing if `AttributeError` is raised. Thus, if the getter method tries calls something  in turn raises `AttributeError` e.g.:

```
@property
def avg_cluster_size(self):
    return self._cpp_obj.thisIsNotAMethod()
```
then Python reports that `avg_cluster_size` is not a property and masks the actual exception that generated the error - which in this case could either be because `thisIsNotAMethod` does't exist or `_cpp_obj` doesn't exist.

@b-butler designed the `__getattr__` system and will be better able to answer any questions on that.

**Comment by joaander** [comment]
I don't think there is anything we can do to improve this given Python's design.
